Titans/projet/src/Entity/Produit.php
<?php

namespace App\Entity;

use App\Repository\ProduitRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ProduitRepository::class)
 */
class Produit
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nom;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $code;

    /**
     * @ORM\Column(type="float")
     */
    private $prix;

    /**
     * @ORM\Column(type="integer")
     */
    private $mrp;

    /**
     * @ORM\Column(type="float")
     */
    private $prix_m;

    /**
     * @ORM\Column(type="float")
     */
    private $tax;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $unite;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $status;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $description;

    /**
     * @ORM\Column(type="text", length=255)
     */
    private $stock;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $image;

    /**
     * @ORM\ManyToOne(targetEntity=Categorie::class, inversedBy="produit")
     * @ORM\JoinColumn(nullable=false)
     */
    private $categorie;

    /**
     * @ORM\ManyToOne(targetEntity=Scategorie::class, inversedBy="produit")
     */
    private $scategorie;
  /**
     * @ORM\OneToMany(targetEntity=Achats::class, mappedBy="produit")
     */
    private $achats;

    /**
     * @ORM\ManyToMany(targetEntity=Vente::class, mappedBy="produits")
     */
    private $ventes;

    public function __construct()
    {
        $this->ventes = new ArrayCollection();
    }
    
   


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getCode(): ?string
    {
        return $this->code;
    }

    public function setCode(string $code): self
    {
        $this->code = $code;

        return $this;
    }

    public function getPrix(): ?float
    {
        return $this->prix;
    }

    public function setPrix(float $prix): self
    {
        $this->prix = $prix;

        return $this;
    }

    public function getMrp(): ?int
    {
        return $this->mrp;
    }

    public function setMrp(int $mrp): self
    {
        $this->mrp = $mrp;

        return $this;
    }

    public function getPrixM(): ?float
    {
        return $this->prix_m;
    }

    public function setPrixM(float $prix_m): self
    {
        $this->prix_m = $prix_m;

        return $this;
    }

    public function getTax(): ?float
    {
        return $this->tax;
    }

    public function setTax(float $tax): self
    {
        $this->tax = $tax;

        return $this;
    }

    public function getUnite(): ?string
    {
        return $this->unite;
    }

    public function setUnite(string $unite): self
    {
        $this->unite = $unite;

        return $this;
    }

    public function getStatus(): ?string
    {
        return $this->status;
    }

    public function setStatus(string $status): self
    {
        $this->status = $status;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getStock(): ?string
    {
        return $this->stock;
    }

    public function setStock(string $stock): self
    {
        $this->stock = $stock;

        return $this;
    }

    public function getImage()
    {
        return $this->image;
    }

    public function setImage( $image)
    {
        $this->image = $image;

        return $this;
    }

    public function getCategorie(): ?Categorie
    {
        return $this->categorie;
    }

    public function setCategorie(?Categorie $categorie): self
    {
        $this->categorie = $categorie;

        return $this;
    }

    public function getScategorie(): ?Scategorie
    {
        return $this->scategorie;
    }

    public function setScategorie(?Scategorie $scategorie): self
    {
        $this->scategorie = $scategorie;

        return $this;
    }

    /**
     * @return Collection|Achats[]
     */
    public function getAchats(): Collection
    {
        return $this->achats;
    }

    public function addAchat(Achats $achat): self
    {
        if (!$this->achats->contains($achat)) {
            $this->achats[] = $achat;
            $achat->setProduit($this);
        }

        return $this;
    }

    public function removeAchat(Achats $achat): self
    {
        if ($this->achats->removeElement($achat)) {
            // set the owning side to null (unless already changed)
            if ($achat->getProduit() === $this) {
                $achat->setProduit(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Vente[]
     */
    public function getVentes(): Collection
    {
        return $this->ventes;
    }

    public function addVente(Vente $vente): self
    {
        if (!$this->ventes->contains($vente)) {
            $this->ventes[] = $vente;
            $vente->addProduit($this);
        }

        return $this;
    }

    public function removeVente(Vente $vente): self
    {
        if ($this->ventes->removeElement($vente)) {
            $vente->removeProduit($this);
        }

        return $this;
    }
 
 
       
    

    

  

}

Titans/projet/src/Form/ProduitType.php
<?php

namespace App\Form;

use App\Entity\Produit;
use App\Entity\Categorie;
use App\Entity\Scategorie;
use App\Form\ScategorieType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\ButtonType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;

class ProduitType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('nom')
            ->add('code')
            ->add('prix')
            ->add('mrp')
            ->add('prix_m')
            ->add('tax')
            ->add('unite')
            ->add('status')
            ->add('description',TextareaType::class)
            ->add('stock')
            ->add('image' , FileType::class, [
                'data_class' => null
            ])
            ->add('try', ButtonType::class, [
                'label' => 'generate',
                'attr' => array(
                    
                    'onclick' => 'myFunction();')
            ])
         
            ->add('categorie', EntityType::class, [
                // looks for choices from this entity
                'data_class' => null,
                'class' => Categorie::class,
                'label' => 'nom de la catégorie',
          // uses the category name property as the visible option string
                'choice_label' => 'nom',])
              
->add('scategorie', EntityType::class, [
    'data_class' => null,
    // looks for choices from this entity
    'class' => Scategorie::class,
 

// uses the category name property as the visible option string
    'choice_label' => 'nom',])

               
     
    ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Produit::class,
           
        ]);
    }
}

Titans/projet/src/Controller/ProduitController.php
<?php

namespace App\Controller;

use App\Entity\Produit;
use App\Form\ProduitType;
use App\Repository\ProduitRepository;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;


/**
 * @Route("/produit")
 */
class ProduitController extends AbstractController
{
    /**
     * @Route("/", name="produit_index", methods={"GET"})
     */
    public function index(ProduitRepository $produitRepository): Response
    {
        return $this->render('produit/index.html.twig', [
            'produits' => $produitRepository->findAll(),
            
        ]);
    }

    /**
     * @Route("/new", name="produit_new", methods={"GET","POST"})
     */
    public function new(Request $request ): Response
    {
        $produit = new Produit();
        $form = $this->createForm(ProduitType::class, $produit);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $file = $produit->getImage();

            $fileName = $this->generateUniqueFileName().'.'.$file->guessExtension();

            // moves the file to the directory where brochures are stored
            $file->move(
                $this->getParameter('brochures_directory'),
                $fileName
            );

            $produit->setImage($fileName);

            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($produit);
            $entityManager->flush();

            return $this->redirectToRoute('produit_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('produit/new.html.twig', [
            'produit' => $produit,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="produit_show", methods={"GET"})
     */
    public function show(Produit $produit): Response
    {
        return $this->render('produit/show.html.twig', [
            'produit' => $produit,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="produit_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Produit $produit): Response
    {
        $form = $this->createForm(ProduitType::class, $produit);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('produit_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('produit/edit.html.twig', [
            'produit' => $produit,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="produit_delete", methods={"POST"})
     */
    public function delete(Request $request, Produit $produit): Response
    {
        if ($this->isCsrfTokenValid('delete'.$produit->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($produit);
            $entityManager->flush();
        }

        return $this->redirectToRoute('produit_index', [], Response::HTTP_SEE_OTHER);
    }
     /**
     * @return string
     */
    private function generateUniqueFileName()
    {
        // md5() reduces the similarity of the file names generated by
        // uniqid(), which is based on timestamps
        return md5(uniqid());
    }

}

Titans/projet/templates/produit/_delete_form.html.twig
<form method="post" action="{{ path('produit_delete', {'id': produit.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ produit.id) }}">
      <button  class="btn btn-sm btn-white text-danger me-2"><i class="far fa-trash-alt me-1"></i>Supprimer</button>
</form>

Titans/projet/templates/produit/_form.html.twig
{{ form_start(form) }}



<div class="page-header">
<div class="row">
<div class="col-sm-12">
<h3 class="page-title">Produits</h3>
<ul class="breadcrumb">
<li class="breadcrumb-item"><a href="index.html">Dashboard</a></li>
<li class="breadcrumb-item"><a href="customers.html">Produits</a></li>
<li class="breadcrumb-item active">Ajouter un produit</li>
</ul>
</div>
</div>
</div>

<div class="row">
<div class="col-md-12">
<div class="card">
<div class="card-body">
<h4  id="theDiv" class="card-title">Ajouter un produit</h4>

<div class="row">
<div class="col-md-6">
<div class="form-group">
{{ form_label(form.nom, 'Nom du produit', {'label_attr': {'class': 'control-label'}}) }}
{{ form_widget(form.nom)}}
</div>


<div class="form-group">
{{ form_label(form.categorie, 'Nom des catégories', {'label_attr': {'class': 'control-label'}}) }}
{{ form_widget(form.categorie,{'attr':{"class" : "select"  }  }) }}
</div>
<div class="form-group">
{{ form_label(form.prix, 'Prix de revient', {'label_attr': {'class': 'control-label'}}) }}
{{ form_widget(form.prix)}}
</div>
<div class="form-group">
{{ form_label(form.prix_m, 'Minimum Retail Price', {'label_attr': {'class': 'control-label'}}) }}
{{ form_widget(form.prix_m)}}
</div>
<div class="form-group">
{{ form_label(form.unite, 'Unité', {'label_attr': {'class': 'control-label'}}) }}
{{ form_widget(form.unite)}}
</div>

<div class="form-group">
{{ form_label(form.description, 'Description', {'label_attr': {'class': 'control-label'}}) }}
{{ form_widget(form.description,  {'attr':{"rows" : "5" , "cols" : "5"  }  }) }}
</div>

</div>
<div class="col-md-6">
<div class="form-group">
{{ form_label(form.code, 'Code du produit', {'label_attr': {'class': 'control-label'}}) }}
{{ form_widget(form.code, { 'id': 'xd' }) }}

{{ form_widget(form.try, { 'attr': {'class': 'foo'}  }) }}

<style>
.foo{
      background-color: #4CAF50; /* Green */
  border: none;
background-color:#BFBFBF;
  color: white;
  padding: 7px 10px;
  text-align: center;
  text-decoration: none;
  display: inline-block;
  position: absolute;
  font-size: 16px;
top:85px;
right:30px;
    float:right;
}
</style>
<script>
//document.getElementById("demo").onclick = function() {myFunction()};

function myFunction() {
const result = Math.random().toString(36).substring(2,7);

  document.getElementById("xd").value = result;
}


</script>

</div>
<div class="form-group">

{{ form_label(form.scategorie, 'Nom des  sous catégories', {'label_attr': {'class': 'control-label'}}) }}
{{ form_widget(form.scategorie,{'attr':{"class" : "select"  }  }) }}

</div>
<div class="form-group">
{{ form_label(form.mrp, 'MRP', {'label_attr': {'class': 'control-label'}}) }}
{{ form_widget(form.mrp)}}
</div>
<div class="form-group">
{{ form_label(form.tax, 'Product Tax', {'label_attr': {'class': 'control-label'}}) }}
{{ form_widget(form.tax, { 'id': 'tax' }) }}
</div>

<div class="form-group">
{{ form_label(form.status, 'Status', {'label_attr': {'class': 'control-label'}}) }}
{{ form_widget(form.status)}}
</div>
<div class="form-group">
{{ form_label(form.stock, 'Opening Stock', {'label_attr': {'class': 'control-label'}}) }}
{{ form_widget(form.stock)}}<br>
{{ form_label(form.image, 'Image', {'label_attr': {'class': 'control-label'}}) }}
{{ form_widget(form.image)}}
</div>
</div>



</div>


<div class="text-end mt-4">

<button type="submit" class="btn btn-primary ">{{ button_label|default('Ajouter ') }}</button>
<button class="btn btn-secondary" type="reset">Cancel</button>

<a href="{{ path('produit_index') }}"  class="btn btn-secondary">Revenir à la liste</a>
</div>

</div>
</div>
</div>
</div>
</div>
</div>









{{ form_end(form) }}

Titans/projet/templates/produit/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Produit{% endblock %}

{% block body %}
   

    {{ include('produit/edit_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('produit_index') }}">back to list</a>

    {{ include('produit/_delete_form.html.twig') }}
{% endblock %}

Titans/projet/templates/produit/edit_form.html.twig
{{ form_start(form) }}



<div class="page-header">
<div class="row">
<div class="col-sm-12">
<h3 class="page-title">Produits</h3>
<ul class="breadcrumb">
<li class="breadcrumb-item"><a href="index.html">Dashboard</a></li>
<li class="breadcrumb-item"><a href="customers.html">Produits</a></li>
<li class="breadcrumb-item active">Modifier un produit</li>
</ul>
</div>
</div>
</div>

<div class="row">
<div class="col-md-12">
<div class="card">
<div class="card-body">
<h4  id="theDiv" class="card-title">Modifier un produit</h4>

<div class="row">
<div class="col-md-6">
<div class="form-group">
{{ form_label(form.nom, 'Nom du produit', {'label_attr': {'class': 'control-label'}}) }}
{{ form_widget(form.nom)}}
</div>


<div class="form-group">
{{ form_label(form.categorie, 'Nom des catégories', {'label_attr': {'class': 'control-label'}}) }}
{{ form_widget(form.categorie,{'attr':{"class" : "select"  }  }) }}
</div>
<div class="form-group">
{{ form_label(form.prix, 'Prix de revient', {'label_attr': {'class': 'control-label'}}) }}
{{ form_widget(form.prix)}}
</div>
<div class="form-group">
{{ form_label(form.prix_m, 'Minimum Retail Price', {'label_attr': {'class': 'control-label'}}) }}
{{ form_widget(form.prix_m)}}
</div>
<div class="form-group">
{{ form_label(form.unite, 'Unité', {'label_attr': {'class': 'control-label'}}) }}
{{ form_widget(form.unite)}}
</div>

<div class="form-group">
{{ form_label(form.description, 'Description', {'label_attr': {'class': 'control-label'}}) }}
{{ form_widget(form.description,  {'attr':{"rows" : "5" , "cols" : "5"  }  }) }}
</div>

</div>
<div class="col-md-6">
<div class="form-group">
{{ form_label(form.code, 'Code du produit', {'label_attr': {'class': 'control-label'}}) }}
{{ form_widget(form.code, { 'id': 'xd' }) }}

{{ form_widget(form.try, { 'attr': {'class': 'foo'} }) }}

<style>
.foo{
      background-color: #4CAF50; /* Green */
  border: none;
background-color:#BFBFBF;
  color: white;
  padding: 7px 10px;
  text-align: center;
  text-decoration: none;
  display: inline-block;
  position: absolute;
  font-size: 16px;
top:85px;
right:30px;
    float:right;
}
</style>
<script>
//document.getElementById("demo").onclick = function() {myFunction()};

function myFunction() {
const result = Math.random().toString(36).substring(2,7);

  document.getElementById("xd").value = result;
}


</script>

</div>
<div class="form-group">

{{ form_label(form.scategorie, 'Nom des  sous catégories', {'label_attr': {'class': 'control-label'}}) }}
{{ form_widget(form.scategorie,{'attr':{"class" : "select"  }  }) }}

</div>
<div class="form-group">
{{ form_label(form.mrp, 'MRP', {'label_attr': {'class': 'control-label'}}) }}
{{ form_widget(form.mrp)}}
</div>
<div class="form-group">
{{ form_label(form.tax, 'Product Tax', {'label_attr': {'class': 'control-label'}}) }}
{{ form_widget(form.tax)}}
</div>

<div class="form-group">
{{ form_label(form.status, 'Status', {'label_attr': {'class': 'control-label'}}) }}
{{ form_widget(form.status)}}
</div>
<div class="form-group">
{{ form_label(form.stock, 'Opening Stock', {'label_attr': {'class': 'control-label'}}) }}
{{ form_widget(form.stock)}}<br>
{{ form_label(form.image, 'Image', {'label_attr': {'class': 'control-label'}}) }}
{{ form_widget(form.image)}}
</div>
</div>



</div>


<div class="text-end mt-4">

<button type="submit" class="btn btn-primary ">{{ button_label|default('Ajouter ') }}</button>
<button class="btn btn-secondary" type="reset">Cancel</button>

<a href="{{ path('produit_index') }}"  class="btn btn-secondary">Revenir à la liste</a>
</div>

</div>
</div>
</div>
</div>
</div>
</div>









{{ form_end(form) }}

Titans/projet/templates/produit/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Produit index{% endblock %}

{% block javascripts %}
{{parent()}}
<script src="{{asset('plugins/datatables/jquery.dataTables.min.js')}}"></script>
<script src="{{asset('plugins/datatables-bs4/js/dataTables.bootstrap4.min.js')}}"></script>
<script src="{{asset('plugins/datatables-responsive/js/dataTables.responsive.min.js')}}"></script>
<script src="{{asset('plugins/datatables-responsive/js/responsive.bootstrap4.min.js')}}"></script>
<script src="{{asset('plugins/datatables-buttons/js/dataTables.buttons.min.js')}}"></script>
<script src="{{asset('plugins/datatables-buttons/js/buttons.bootstrap4.min.js')}}"></script>
<script src="{{asset('plugins/jszip/jszip.min.js')}}"></script>
<script src="{{asset('plugins/pdfmake/pdfmake.min.js')}}"></script>
<script src="{{asset('plugins/pdfmake/vfs_fonts.js')}}"></script>
<script src="{{asset('plugins/datatables-buttons/js/buttons.html5.min.js')}}"></script>
<script src="{{asset('plugins/datatables-buttons/js/buttons.print.min.js')}}"></script>
<script src="{{asset('plugins/datatables-buttons/js/buttons.colVis.min.js')}}"></script>
<script src="{{asset('dist/js/adminlte.min.js')}}"></script>
<script>
  $(function () {
    $("#example1").DataTable({
      "responsive": true, "lengthChange": false, "autoWidth": false,
    }).buttons().container().appendTo('#example1_wrapper .col-md-6:eq(0)');
    $('#example2').DataTable({
      "paging": true,
      "lengthChange": false,
      "searching": false,
      "ordering": true,
      "info": true,
      "autoWidth": false,
      "responsive": true,
    });
  });
</script>
{% endblock %}
{% block body %}
    
   
<div class="page-header">
<div class="row align-items-center">
<div class="col">
<h3 class="page-title">Produits</h3>
<ul class="breadcrumb">
<li class="breadcrumb-item"><a href="index.html">Dashboard</a>
</li>
<li class="breadcrumb-item active">Produits</li>
</ul>
</div>
<div class="col-auto">
<a href="{{ path('produit_new') }}" class="btn btn-primary me-1">
<i class="fas fa-plus" title="Ajouter un produit"></i>
</a>

</div>
</div>
</div>

<div class="row">
<div class="col-sm-12">
<div class="card card-table">
<div class="card-body">
<div class="table-responsive">
<table id="example1" class="table">
<thead class="thead-light">
<tr>
<th>ID</th>
<th>Produit</th>
<th>En Stock</th>
<th>Total</th>



<th style=" position:relative; left:350px; " >Actions</th>
</tr>
</thead>
<tbody>
    {% for produit in produits %}
<tr>
<td>{{ produit.id }}</td>
<td>{{ produit.nom }} ({{produit.code}})</td>
<td>{{produit.stock}} </td>
<td>{{produit.prix  + produit.prixm}} </th>

 {# <td><img src="/uploads/photos/{{produit.image}}" height="42" width="42"></td> #}


                
<td>

<div style="
    float: right;top: 160px;
    right: 200px;"> {{ include('produit/_delete_form.html.twig') }}  </div>
<a style="float:right "href="{{ path('produit_edit', {'id': produit.id}) }}" class="btn btn-sm btn-white text-success me-2"><i class="far fa-edit me-1"></i> Editer</a>
<a style="float:right" href="{{ path('produit_show', {'id': produit.id}) }}" class="btn btn-sm btn-primary  "><i class="far fa-eye me-1"></i>Afficher</a>

</td>
</tr>
 {% else %}
            <tr>
                <td colspan="3">no records found</td>
            </tr>
        {% endfor %}
</tbody>
</table>
</div>
</div>
</div>
</div>
</div>
</div>
</div>

</div>
{% endblock %}

Titans/projet/templates/produit/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Produit{% endblock %}

{% block body %}
  

    {{ include('produit/_form.html.twig') }}

    <a href="{{ path('produit_index') }}">back to list</a>
{% endblock %}

Titans/projet/templates/produit/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Produit{% endblock %}

{% block body %}
    <h1>Produit</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ produit.id }}</td>
            </tr>
            <tr>
                <th>Nom</th>
                <td>{{ produit.nom }}</td>
            </tr>
            <tr>
                <th>Code</th>
                <td>{{ produit.code }}</td>
            </tr>
            <tr>
                <th>Prix</th>
                <td>{{ produit.prix }}</td>
            </tr>
            <tr>
                <th>Mrp</th>
                <td>{{ produit.mrp }}</td>
            </tr>
            <tr>
                <th>Prix_m</th>
                <td>{{ produit.prixM }}</td>
            </tr>
            <tr>
                <th>Tax</th>
                <td>{{ produit.tax }}</td>
            </tr>
            <tr>
                <th>Unite</th>
                <td>{{ produit.unite }}</td>
            </tr>
            <tr>
                <th>Status</th>
                <td>{{ produit.status }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ produit.description }}</td>
            </tr>
            <tr>
                <th>Stock</th>
                <td>{{ produit.stock }}</td>
            </tr>
            <tr>
                <th>Image</th>
                <td>{{ produit.image }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('produit_index') }}">back to list</a>

    <a href="{{ path('produit_edit', {'id': produit.id}) }}">edit</a>

    {{ include('produit/_delete_form.html.twig') }}
{% endblock %}