Titans/projet/src/Entity/Vente.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use App\Repository\VenteRepository;
use Symfony\Component\Validator\Constraints\Date;
use Symfony\Component\Validator\Constraints\DateTime;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
/**
 * @ORM\Entity(repositoryClass=VenteRepository::class)
 */
class Vente
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;
 


    /**
     * @ORM\ManyToOne(targetEntity=Client::class, inversedBy="ventes")
     */
    private $client;

    /**
     * @ORM\Column(type="integer")
     */
    private $quantite;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $modePaie;

    /**
     * @ORM\Column(type="float")
     */
    private $prix_u;
  /**
 * @var \Date
 * @Gedmo\Mapping\Annotation\Timestampable(on="create")
 * @Doctrine\ORM\Mapping\Column(type="date")
 */
public $createdAt;

/**
 * @ORM\ManyToMany(targetEntity=Produit::class, inversedBy="ventes")
 */
private $produits;

public function __construct()
{
    $this->produits = new ArrayCollection();
}
    public function getId(): ?int
    {
        return $this->id;
    }

  

    public function getClient(): ?Client
    {
        return $this->client;
    }

    public function setClient(?Client $client): self
    {
        $this->client = $client;

        return $this;
    }

    public function getQuantite(): ?int
    {
        return $this->quantite;
    }

    public function setQuantite(int $quantite): self
    {
        $this->quantite = $quantite;

        return $this;
    }

    public function getModePaie(): ?string
    {
        return $this->modePaie;
    }

    public function setModePaie(string $modePaie): self
    {
        $this->modePaie = $modePaie;

        return $this;
    }

    public function getPrixU(): ?float
    {
        return $this->prix_u;
    }

    public function setPrixU(float $prix_u): self
    {
        $this->prix_u = $prix_u;

        return $this;
    }

    /**
     * @return Collection|Produit[]
     */
    public function getProduits(): Collection
    {
        return $this->produits;
    }

    public function addProduit(Produit $produit): self
    {
        if (!$this->produits->contains($produit)) {
            $this->produits[] = $produit;
        }

        return $this;
    }

    public function removeProduit(Produit $produit): self
    {
        $this->produits->removeElement($produit);

        return $this;
    }
    public function __tostring(){
        return $this->nom;
    }

    
   

}

Titans/projet/src/Form/VenteType.php
<?php

namespace App\Form;

use App\Entity\Vente;
use App\Entity\Client;
use App\Entity\Produit;
use Symfony\Component\Form\FormEvents;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;

class VenteType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('quantite')
            ->add('modePaie', ChoiceType::class, [
                'choices' => [
                    'Espece'=>'Espece',
                    'Cheque' => 'Cheque'
                ],
                'placeholder'=> 'Selectionnez Le Mode De paiement'
            ])

            
            ->add('produits', EntityType::class, array(
                'class' => Produit::class,
              
                'choice_label' => 'nom',
                'multiple' => true,
                'expanded' => true,
                'required' => false))

                ->add('client', EntityType::class, [
                    // looks for choices from this entity
                    'class' => Client::class,
                    'label' => 'Client',
                    'placeholder'=> 'Selectionnez Un Client',
              // uses the category name property as the visible option string
                    'choice_label' => 'nom',])
                    ->add('prix_u')
        ;




                }
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Vente::class,
        ]);
    }
}

Titans/projet/src/Controller/VenteController.php
<?php

namespace App\Controller;

use App\Entity\Vente;
use App\Form\VenteType;
use App\Repository\ProduitRepository;
use App\Repository\VenteRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/vente")
 */
class VenteController extends AbstractController
{
    /**
     * @Route("/", name="vente_index", methods={"GET"})
     */
    public function index(VenteRepository $venteRepository , ProduitRepository $p): Response
    {
        return $this->render('vente/index.html.twig', [
            'ventes' => $venteRepository->findAll(),
            'produits' => $p->findAll()
        ]);
    }

    /**
     * @Route("/new", name="vente_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $vente = new Vente();
        $form = $this->createForm(VenteType::class, $vente);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($vente);
            $entityManager->flush();

            return $this->redirectToRoute('vente_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('vente/new.html.twig', [
            'vente' => $vente,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="vente_show", methods={"GET"})
     */
    public function show(Vente $vente): Response
    {
        return $this->render('vente/show.html.twig', [
            'vente' => $vente,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="vente_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Vente $vente): Response
    {
        $form = $this->createForm(VenteType::class, $vente);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('vente_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('vente/edit.html.twig', [
            'vente' => $vente,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="vente_delete", methods={"POST"})
     */
    public function delete(Request $request, Vente $vente): Response
    {
        if ($this->isCsrfTokenValid('delete'.$vente->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($vente);
            $entityManager->flush();
        }

        return $this->redirectToRoute('vente_index', [], Response::HTTP_SEE_OTHER);
    }
}

Titans/projet/templates/vente/_delete_form.html.twig
<form method="post" action="{{ path('vente_delete', {'id': vente.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ vente.id) }}">
          <button  class="btn btn-sm btn-white text-danger me-2"><i class="far fa-trash-alt me-1"></i>Supprimer</button>
</form>

Titans/projet/templates/vente/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

Titans/projet/templates/vente/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Vente{% endblock %}

{% block body %}
    <h1>Edit Vente</h1>

    {{ include('vente/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('vente_index') }}">back to list</a>

    {{ include('vente/_delete_form.html.twig') }}
{% endblock %}

Titans/projet/templates/vente/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Vente index{% endblock %}

{% block body %}

   
<div class="page-header">
<div class="row align-items-center">
<div class="col">
<h3 class="page-title">Ventes</h3>
<ul class="breadcrumb">
<li class="breadcrumb-item"><a href="index.html">Dashboard</a>
</li>
<li class="breadcrumb-item active">Ventes</li>
</ul>
</div>
<div class="col-auto">
<a href="{{ path('vente_new') }}" class="btn btn-primary me-1">
<i class="fas fa-plus"></i>
</a>

</div>
</div>
</div>

<div class="row">
<div class="col-sm-12">
<div class="card card-table">
<div class="card-body">
<div class="table-responsive">
<table  id="example1" class="table ">
<thead class="thead-light">
    <tr>
<th>ID</th>
<th>quantite</th>
<th>Mode de paiement</th>
<th>Prix</th>



<th style="  position:relative; left:350px; ">Actions</th>
</tr>
</thead>
<tbody>
       {% for vente in ventes %}

<tr>
<td>{{vente.id}}
<td>{{ vente.quantite }}</td>
                <td>{{ vente.modePaie }}</td>
                    <td>{{vente.prixu}}</td>
       
           

                
                
<td>

<div style="
    float: right;top: 160px;
    right: 200px;"> {{ include('vente/_delete_form.html.twig') }}  </div>
<a style="float:right "href="{{ path('vente_edit', {'id': vente.id}) }}" class="btn btn-sm btn-white text-success me-2"><i class="far fa-edit me-1"></i> Edit</a>
<a style="float:right" href="{{ path('vente_show', {'id': vente.id}) }}" class="btn btn-sm btn-primary  "><i class="far fa-eye me-1"></i>Afficher</a>
</td>
</tr>
 {% else %}
            <tr>
                <td colspan="3">no records found</td>
            </tr>
        {% endfor %}
</tbody>
</table>
</div>
</div>
</div>
</div>
</div>
</div>
</div>

</div>
{% endblock %}

{% block javascripts %}
{{parent()}}
<script src="{{asset('plugins/datatables/jquery.dataTables.min.js')}}"></script>
<script src="{{asset('plugins/datatables-bs4/js/dataTables.bootstrap4.min.js')}}"></script>
<script src="{{asset('plugins/datatables-responsive/js/dataTables.responsive.min.js')}}"></script>
<script src="{{asset('plugins/datatables-responsive/js/responsive.bootstrap4.min.js')}}"></script>
<script src="{{asset('plugins/datatables-buttons/js/dataTables.buttons.min.js')}}"></script>
<script src="{{asset('plugins/datatables-buttons/js/buttons.bootstrap4.min.js')}}"></script>
<script src="{{asset('plugins/jszip/jszip.min.js')}}"></script>
<script src="{{asset('plugins/pdfmake/pdfmake.min.js')}}"></script>
<script src="{{asset('plugins/pdfmake/vfs_fonts.js')}}"></script>
<script src="{{asset('plugins/datatables-buttons/js/buttons.html5.min.js')}}"></script>
<script src="{{asset('plugins/datatables-buttons/js/buttons.print.min.js')}}"></script>
<script src="{{asset('plugins/datatables-buttons/js/buttons.colVis.min.js')}}"></script>
<script src="{{asset('dist/js/adminlte.min.js')}}"></script>
<script>
  $(function () {
    $("#example1").DataTable({
      "responsive": true, "lengthChange": false, "autoWidth": false,
    }).buttons().container().appendTo('#example1_wrapper .col-md-6:eq(0)');
    $('#example2').DataTable({
      "paging": true,
      "lengthChange": false,
      "searching": false,
      "ordering": true,
      "info": true,
      "autoWidth": false,
      "responsive": true,
    });
  });
</script>
{% endblock %}

Titans/projet/templates/vente/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Vente{% endblock %}

{% block body %}
    <h1>Create new Vente</h1>

    {{ include('vente/_form.html.twig') }}

    <a href="{{ path('vente_index') }}">back to list</a>
{% endblock %}

Titans/projet/templates/vente/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Vente{% endblock %}

{% block body %}
    <h1>Vente</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ vente.id }}</td>
            </tr>
            <tr>
                <th>Quantite</th>
                <td>{{ vente.quantite }}</td>
            </tr>
            <tr>
                <th>ModePaie</th>
                <td>{{ vente.modePaie }}</td>
            </tr>
            <tr>
                <th>Prix_u</th>
                <td>{{ vente.prixU }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('vente_index') }}">back to list</a>

    <a href="{{ path('vente_edit', {'id': vente.id}) }}">edit</a>

    {{ include('vente/_delete_form.html.twig') }}
{% endblock %}